export * from '@ctx-core/fetch'
export * from './assign_undici_to_globalThis.js'
export * from './fetch_response_pair_.js'
export * from './headers_.js'
export { fetch, Headers, Request, Response } from './undici-fetch/index.js'
